openapi: 3.0.1
info:
  title: Eligibility Signposting API
  version: 1.0.8-alpha
  description: "## Overview\n Use this API to access the [Eligibility Signposting API](https://digital.nhs.uk/services/eligibility-signposting) - the nationally curated single source of eligibility status and signposted actions for individuals.  For example, you can request eligibility for one or more vaccination types to understand if NHS England holds information which suggest that the person could or should take further steps toward receiving those vaccinations, and optionally, a list of the steps NHS England would recommend.\n \n Where someone is deemed eligible, they will also be classified as actionable or not actionable. When deemed not actionable, a reason will be returned.  These reasons can range from personal care setting impacts to current lack of availability of vaccines and more.\n \n The API returns most of its data in both codes and text.  Unless agreed with NHS England, where text is provided it should be displayed to the user as-is.\n \n This API currently has a single User Restricted access mode and will operate only in the context of the authenticated individual, you may however request:\n * eligibility for all supported vaccinations\n * eligibility for specified supported vaccinations\n * request that actions be included in the response\n * request that actions not be included in the response\n \n You cannot currently use this API to:\n * request eligibility for proxy people (familial relations etc.)\n * request actions for people considered ineligible\n \n This API is read-only and can return a list of processed suggestions, each relating to a 'condition' (e.g. COVID, RSV, BOWEL, EYE, BREAST etc.), including the following information for each:\n * a code representing the condition (COVID, RSV, BOWEL, EYE, BREAST)\n * an overall status (NotEligible, NotActionable, Actionable)\n * a list of eligibility cohort groups to which the person belongs (when eligible)\n * a list of the cohort groups that could have made the person eligible (when not eligible)\n * a list of rules/reasons that deem a person to be NotActionable\n * a list of actions that should be shown to the consumer\n \n #### Definitions of Overall Status \n \nThe overall status values indicate the following:\n \n* NotEligible - the individual does not currently meet eligibility criteria\n* NotActionable - the individual is eligible but does not need to take any further action at this time\n* Actionable - the individual is eligible and should follow one of the recommended actions provided\n \n### Patients included in the Eligibility Signposting API\n The API will return data for all patients who are in the NHS PDS system that are registered with an English GP practice (or one administered by England) or who we believe to be resident in England. \n \n Patients who are deceased (or thought to be), marked as invalid or sensitive will not be processed by this API.\n \n ## Who can use this API\n This API can only be used where there is a [legal basis](https://digital.nhs.uk/services/eligibility-signposting/legal-basis) to do so. Make sure you have a valid use case before you go too far with your development.  You must demonstrate you have a [valid use case](https://digital.nhs.uk/services/eligibility-signposting/legal-basis) as part of digital onboarding. \n \n You must do this before you can go live (see 'Onboarding' below).\n \n ### Who can access Eligibility Signposting Information\n Patients who receive health and social care or make use of NHS services in England, Wales and the Isle of Man can access their own Eligibility Signposting data through onboarded services.\n \n Health and care organisations in England and the Isle of Man can access our information for legitimate direct care purposes. Legitimate direct care examples include NHS organisations delivering healthcare, local authorities delivering care, third sector and private sector health and care organisations, and developers delivering systems to health and care organisations. \n \n \n ### Existing API users\n To find out which healthcare software development organisations and products are already using this API, see [Eligibility Signposting API - integrated products](https://digital.nhs.uk/services/eligibility-signposting/integrated-products).\n \n ## Access modes\n This API currently has only one access mode:\n * patient access \n \n We are considering the possibility of adding other modes in the future:\n * healthcare worker access \n * restricted access \n \n ### Patient access \n If the end user is a patient then you must use this access mode. Use this access mode to obtain data for that patient.\n \n This access mode is [user-restricted](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis), meaning an end user must be present, authenticated and authorised. \n \n The end user must be: \n * a patient who receives health and social care or makes use of NHS services \n * strongly authenticated, using [NHS login](https://digital.nhs.uk/services/nhs-login)\n \n To use this access mode, use one of the following security patterns:\n \n |\tSecurity pattern\t\t                                                                                                                                                                                                          |\tTechnical details\t                                  |\tAdvantages\t                                                | Disadvantages                                           |\n |-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------| ----------------------------------------------------| ------------------------------------------------------------|---------------------------------------------------------|\n |[NHS login - combined authentication and authorisation](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/user-restricted-restful-apis-nhs-login-combined-authentication-and-authorisation) |OAuth 2.0 authorisation code with API key and secret |No need to integrate and onboard separately with NHS login.  |No access to user information.                           |\n |[NHS login - separate authentication and authorisation](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/user-restricted-restful-apis-nhs-login-separate-authentication-and-authorisation) |OAuth 2.0 token exchange with signed JWT             |Gives access to user information.                            |Need to integrate and onboard separately with NHS login. |\n \n Patient access mode users must be authenticated to a high proofing level (P9) and to one of the following [vectors of trust](https://nhsconnect.github.io/nhslogin/vectors-of-trust/): \n * P9.Cp.Cd\n * P9.Cp.Ck\n * P9.Cm\n \n This access mode is available in production ([beta](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#api-status)).\n \n ### Restricted access\n This access mode is not yet available, if you believe this mode would benefit your use-case, please let us know.\n \n This access mode is [application-restricted](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#application-restricted-apis), meaning we authenticate and authorise the calling application but not the end user. \n \n This access mode is not designed to be accessed by an end user. You might use this access mode as part of a back-end process to: \n * retrieve eligibility signposting information into a system in advance of a clinic\n * retrieve eligibility signposting information into a system to be used in a disconnected manner\n \n To use this access mode, use this security pattern:\n * [Application-restricted RESTful API - signed JWT authentication](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/application-restricted-restful-apis-signed-jwt-authentication)\n \n ## Roadmap\n The [Eligibility Signposting API](https://digital.nhs.uk/services/eligibility-signposting/roadmap-and-strategy) roadmap shows the planned changes for the API. \n \n To see our roadmap, or to suggest, comment or vote on features for this API, see our [interactive product backlog](https://nhs-digital-api-management.featureupvote.com/suggestions/612352/eligibility-signposting-api-vaccinations).\n \n If you have any other queries, please [contact us](https://digital.nhs.uk/developer/help-and-support).\n \n ## Service level\n \n This API is a silver service, meaning it is operational 24 hours a day, 365 days a year and supported 8am to 6pm, Monday to Friday excluding bank holidays.\n \n For more details, see [service levels](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#service-levels).\n \n ## Rate limits\n \n The default rate limit is 25TPS (Transactions Per Second), per app. If you require a higher rate limit please [contact us](https://digital.nhs.uk/developer/help-and-support). or raise this during the onboarding process.\n \n ## Technology\n This API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/our-api-technologies#basic-rest).\n \n ## Network access\n This API is available on the internet and, indirectly, on the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network).\n \n For more details see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis).\n \n ## Errors\n We use standard HTTP status codes to show whether an API request succeeded or not. They are usually in the range:\n \n * 200 to 299 if it succeeded, including code 202 if it was accepted by an API that needs to wait for further action\n * 400 to 499 if it failed because of a client error by your application\n * 500 to 599 if it failed because of an error on our server\n \n Errors specific to each API are shown in the Endpoints section, under Response. See our [reference guide](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#http-status-codes) for more on errors.\n \n Your API-calling application should have a mechanism to automatically try again, for example by giving status information to your end user, before giving up. See our [reference guide](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#error-handling) for more information about error handling.\n \n ## Open source\n You might find the following [open source](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#open-source) resources useful:\n \n | Resource                  | Description                                                          | Links                                                                          |\n |---------------------------|----------------------------------------------------------------------|--------------------------------------------------------------------------------|\n | Eligibility Signposting API| Source code including API proxy, sandbox and specification and code.      | [GitHub repo](https://github.com/NHSDigital/eligibility-signposting-api) |\n \n We currently don't have any open source client libraries or sample code for this API. If you think this would be useful, you can [upvote the suggestion on our Interactive Product Backlog](https://nhs-digital-api-management.featureupvote.com/suggestions/107439/client-libraries-and-reference-implementations).\n \n \n \n ## Environments and testing\n \n | Environment       | Base URL                                                               |\n | ----------------- | ---------------------------------------------------------------------- |\n | Sandbox           | `https://sandbox.api.service.nhs.uk/eligibility-signposting/eligibility-check`    |\n | Integration test  | `https://int.api.service.nhs.uk/eligibility-signposting/eligibility-check`        |\n | Production        | `https://api.service.nhs.uk/eligibility-signposting/eligibility-check`            |\n \n ### Sandbox testing\n Our [sandbox environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#sandbox-testing):\n * is for early developer testing\n * only covers a limited set of scenarios\n * is open access, so does not allow you to test authorisation\n \n For details of sandbox test scenarios, or to try out the sandbox using our 'Try this API' feature, see the documentation for each endpoint.\n \n Alternatively, you can try out the sandbox using our Postman collection:\n \n [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/?????????????????????????????????)\n \n ### Integration testing\n Our [integration test environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing):\n * is for formal integration testing\n * includes authorisation, with options for user-restricted access (NHS Login) \n ### Production smoke testing\n You must not use real patient data for smoke testing in the production environment.\n \n Rather, use our [production test patient](https://digital.nhs.uk/services/eligibility-signposting/api-test-data#production-smoke-testing).\n \n ## Onboarding\n You need to get your software approved by us before it can go live with this API. We call this onboarding. The onboarding process can sometimes be quite long, so it is worth planning well ahead.\n \n As part of this process, you need to demonstrate your technical conformance to the requirements for this API. \n \n You also need to demonstrate that you can manage risks. This might impact the design of your software. For details, see [Onboarding support information](https://digital.nhs.uk/services/eligibility-signposting/onboarding-support-information).\n \n To understand how our online digital onboarding process works, see [digital onboarding](https://digital.nhs.uk/developer/guides-and-documentation/digital-onboarding). \n \n \n ## Related APIs\n \n The following APIs are related to this API:\n\n"
  contact:
    url: https://developer.nhs.uk/apis/eligibility-signposting-api
  termsOfService: https://developer.nhs.uk/apis/eligibility-signposting-api
tags:
  - name: Eligibility
  - name: Signposting
  - name: NextActions
servers:
  - url: https://sandbox.api.service.nhs.uk/eligibility-signposting
    description: Sandbox Server
  - url: https://int.api.service.nhs.uk/eligibility-signposting
    description: Integration Server
  - url: https://api.service.nhs.uk/eligibility-signposting
    description: Production Server
paths:
  /eligibility-check:
    get:
      summary: Check Eligibility
      description: >-
        Determines which suggestions a person is eligible for and which they are
        not, including reasons and next steps.
      security:
        - nhs-login-p9: []
      operationId: checkEligibility
      parameters:
        - name: patient
          in: query
          required: true
          schema:
            type: string
            example: '9876543210'
          description: The NHS number of the person.
        - name: category
          in: query
          required: false
          schema:
            type: string
            example: VACCINATIONS
            default: ALL
            enum:
              - VACCINATIONS
              - SCREENING
              - ALL
          description: >-
            The category for which the caller is checking eligibility
            suggestions. If not provided, eligibility for all supported
            categories will be checked.
        - name: conditions
          in: query
          required: false
          schema:
            type: string
            example: FLU,RSV
            default: ALL
          description: >-
            The diseases or conditions for which the caller is checking
            eligibility suggestions in a comma separated list. If not provided, eligibility for all
            supported diseases will be checked.
        - name: includeActions
          in: query
          required: false
          schema:
            type: string
            example: Y
            default: Y
            enum:
              - Y
              - N
          description: >-
            When Y is passed in, the API will include one or more actions as applicable.  Passing in N will result in no actions being calculated or returned.
      responses:
        '200':
          description: Eligibility response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseId:
                    type: string
                    description: GUID assigned when the decisioning evaluation is carried out.  This will be useful if you ever need to request support for a particular request.  This will not change if you receive a cached response.
                    example: 1a233ba5-e1eb-4080-a086-2962f6fc3473
                  meta:
                    type: object
                    properties:
                      lastUpdated:
                        type: string
                        description: Timestamp of when the decisioning evaluation is carried out.  This will not change if you receive a cached response.
                        example: '2025-02-12T16:11:22+00:00'
                  processedSuggestions:
                    type: array
                    description: List of suggestions the person is eligible for.
                    items:
                      type: object
                      properties:
                        condition:
                          type: string
                          example: RSV
                          description: String representing the vaccine target disease, screening target or other scenario requiring decision based suggestions, that this suggestion relates to
                        status:
                          type: string
                          example: Actionable
                          description: String representing an overall summary of the persons status for this processedSuggestion
                          enum:
                            - NotEligible
                            - NotActionable
                            - Actionable
                        statusText:
                          type: string
                          example: Actionable - Individual is eligible and we suggest that they follow one or more of the provided actions
                        eligibilityCohorts:
                          type: array
                          description: Cohorts that drove the eligibility status returned.
                          items:
                            type: object
                            properties:
                              cohortCode:
                                type: string
                                description: Machine readable code signifying the cohort/cohort group that lead to a person's eligibility for this suggestion
                              cohortText:
                                type: string
                                description: Human readable (render-able) text describing the meaning of a cohort/cohort group that lead to a person's eligibility for this suggestion
                              cohortStatus:
                                type: string
                                description: String representing the persons status for this processedSuggestion in respect of this particular cohort or cohort group
                                enum:
                                  - NotEligible
                                  - NotActionable
                                  - Actionable
                          example:
                              - cohortCode: 'rsv_75-79_initial'
                                cohortText: You turned 80 after 1 September 2024, so are eligible for the RSV vaccine until 31 August 2025
                                cohortStatus: NotEligible
                              - cohortCode: 'rsv_75-79_ongoing'
                                cohortText: You're aged 75 to 79
                                cohortStatus: Actionable
                        suitabilityRules:
                          type: array
                          description: Reasons that the eligibility status was changed from the base eligibility to result in it's status to not be eligible or to be acted on
                          items:
                            type: object
                            properties:
                              ruleType:
                                type: string
                                description: The type of a rule that triggered to amend the status of the suggestion
                                enum:
                                  - F
                                  - S
                              ruleCode:
                                type: string
                                description: Machine readable code signifying a rule that amended the status of the suggestion
                              ruleText:
                                type: string
                                description: Human readable (render-able) text describing a rule that amended the status of the suggestion
                        actions:
                          type: array
                          description: List of actions to be shown to the person.
                          items:
                            type: object
                            properties:
                              actionType:
                                type: string
                                description: Type of action to render.  E.g. A primary button, a link, text etc
                              actionCode:
                                type: string
                                description: Code representing the action to be taken
                              description:
                                type: string
                                description: A brief description of the step.
                              urlLink:
                                type: string
                                description: URL to invoke if action selected.
              examples:
                example_50000000001:
                  summary: RSV - Actionable CP Booking
                  value:
                    responseId: 1a233ba5-e1eb-4080-a086-2962f6fc3473
                    meta:
                      lastUpdated: '2025-02-12T16:11:22Z'
                    processedSuggestions:
                      - condition: RSV
                        status: Actionable
                        statusText: Actionable - Individual is eligible and we suggest that they follow one or more of the provided actions
                        eligibilityCohorts:
                          - cohortCode: rsv_75-79_ongoing
                            cohortText: You're aged 75 to 79
                            cohortStatus: Actionable
                        actions:
                          - actionType: PrimaryButton
                            actionCode: NationalCPBook
                            description: Book or Amend an RSV vaccinations appointment
                            urlLink: http://www.nhs.uk/book-rsv
                          - actionType: InfoText
                            actionCode: AwaitGPContact
                            description: You can wait for your GP surgery to contact you about getting the RSV vaccine. This may be by letter, text, phone call or email.
                example_50000000002:
                  summary: RSV - Actionable Not CP Booking
                  value:
                    responseId: 1a233ba5-e1eb-4080-a086-2962f6fc3002
                    meta:
                      lastUpdated: '2025-02-12T16:11:22Z'
                    processedSuggestions:
                      - condition: RSV
                        status: Actionable
                        statusText: Actionable - Individual is eligible and we suggest that they follow one or more of the provided actions
                        eligibilityCohorts:
                          - cohortCode: rsv_75-79_ongoing
                            cohortText: You're aged 75 to 79
                            cohortStatus: Actionable
                        actions:
                          - actionType: InfoText
                            actionCode: AwaitGPContact
                            description: You can wait for your GP surgery to contact you about getting the RSV vaccine. This may be by letter, text, phone call or email.
                          - actionType: InfoText
                            actionCode: InfoCPBook
                            description: People in some parts of England are able to book for an RSV vaccination in Community Pharmacies.  Unfortunately, your area does not yet offer RSV vaccinations in that way.  You may be able to receive other vaccinations in pharmacies (such as Flu or COVID)
                example_50000000003:
                  summary: RSV - Eligible, not actionable
                  value:
                    responseId: 1a233ba5-e1eb-4080-a086-2962f6fc3003
                    meta:
                      lastUpdated: '2025-02-12T16:11:22Z'
                    processedSuggestions:
                      - condition: RSV
                        status: NotActionable
                        statusText: Actionable - Individual is eligible but suggest that they need not take any action at this time
                        eligibilityCohorts:
                          - cohortCode: rsv_75-79_ongoing
                            cohortText: You're aged 75 to 79
                            cohortStatus: NotActionable
                        suitabilityRules:
                          - ruleType: S
                            ruleCode: AwaitVaccination
                            ruleText: You are in a setting or organisation that will arrange your vaccination for you.  For example, if you are in a Care Home or a member of some government organisations.
                example_50000000004:
                  summary: RSV - Not Eligible Due to Vaccination
                  value:
                    responseId: 1a233ba5-e1eb-4080-a086-2962f6fc3004
                    meta:
                      lastUpdated: '2025-02-12T16:11:22Z'
                    processedSuggestions:
                      - condition: RSV
                        status: NotEligible
                        statusText: NotEligible - Individual is not currently eligible
                        eligibilityCohorts:
                          - cohortCode: rsv_75-79_ongoing
                            cohortText: You're aged 75 to 79
                            cohortStatus: NotEligible
                        suitabilityRules:
                          - ruleType: F
                            ruleCode: AlreadyVaccinated
                            ruleText: You have already have an RSV vaccination recorded
                example_50000000005:
                  summary: RSV - Not Eligible Due to not being cohorted
                  value:
                    responseId: 1a233ba5-e1eb-4080-a086-2962f6fc3005
                    meta:
                      lastUpdated: '2025-02-12T16:11:22Z'
                    processedSuggestions:
                      - condition: RSV
                        status: NotEligible
                        statusText: NotEligible - Individual is not currently eligible
                        eligibilityCohorts:
                          - cohortCode: rsv_75-79_ongoing
                            cohortText: You're aged 75 to 79
                            cohortStatus: NotEligible
                          - cohortCode: rsv_75-79_initial
                            cohortText: You turned 80 after 1 September 2024, so are eligible for the RSV vaccine until 31 August 2025
                            cohortStatus: NotEligible
                example_50000000006:
                  summary: RSV - No rules
                  value:
                    responseId: 1a233ba5-e1eb-4080-a086-2962f6fc3006
                    meta:
                      lastUpdated: '2025-02-12T16:11:22Z'
        '400':
          description: Invalid input data.
          content:
            application/fhir+json:
              schema:
                type: object
                properties:
                  resourceType:
                    type: string
                    example: OperationOutcome
                  id:
                    type: string
                    example: rrt-2959959087381887325-c-geu2-24001-99999999-1
                  meta:
                    type: object
                    properties:
                      lastUpdated:
                        type: string
                        example: 2025-02-11T14:40:00+00:00
                  issue:
                    type: array
                    items:
                      type: object
                      properties:
                        severity:
                          type: string
                          example: "error"
                        code:
                          type: string
                          example: value
                        details:
                          type: object
                          properties:
                            coding:
                              type: array
                              items:
                                type: object
                                properties:
                                  system:
                                    type: string
                                    example: https://fhir.nhs.uk/CodeSystem/Spine-ErrorOrWarningCode
                                  code:
                                    type: string
                                    example: VALIDATION_ERROR
                                  display:
                                    type: string
                                    example: The given conditions were not not in the expected format.
                        diagnostics:
                          type: string
                          example: 'FLU&COVID should be a single or comma separated list of condition strings with no other punctuation or special characters'
                        location:
                          type: array
                          items:
                            type: string
                            example: 'parameters/conditions'
        '404':
          description: Person not found.
          content:
            application/fhir+json:
              schema:
                type: object
                properties:
                  resourceType:
                    type: string
                    example: OperationOutcome
                  id:
                    type: string
                    example: rrt-2959959087381887325-c-geu2-24001-82918062-1
                  meta:
                    type: object
                    properties:
                      lastUpdated:
                        type: string
                        example: 2025-02-14T11:35:00+00:00
                  issue:
                    type: array
                    items:
                      type: object
                      properties:
                        severity:
                          type: string
                          example: "error"
                        code:
                          type: string
                          example: processing
                        details:
                          type: object
                          properties:
                            coding:
                              type: array
                              items:
                                type: object
                                properties:
                                  system:
                                    type: string
                                    example: https://fhir.nhs.uk/CodeSystem/Spine-ErrorOrWarningCode
                                  code:
                                    type: string
                                    example: RESOURCE_NOT_FOUND
                                  display:
                                    type: string
                                    example: The given NHS number was not found in our datasets.  This could be because the number is incorrect or some other reason we cannot process that number.
                        diagnostics:
                          type: string
                          example: 'NHS Number 9000000404 was not recognised by the Eligibilty Signposting API'
                        location:
                          type: array
                          items:
                            type: string
                            example: 'parameters/patient'
        '422':
          description: 'Unrecognised input data. (Unprocessable Content)'
          content:
            application/fhir+json:
              schema:
                type: object
                properties:
                  resourceType:
                    type: string
                    example: OperationOutcome
                  id:
                    type: string
                    example: rrt-2959959087381887325-c-geu2-24001-88888888-1
                  meta:
                    type: object
                    properties:
                      lastUpdated:
                        type: string
                        example: 2025-02-11T14:40:00+00:00
                  issue:
                    type: array
                    items:
                      type: object
                      properties:
                        severity:
                          type: string
                          example: "error"
                        code:
                          type: string
                          example: value
                        details:
                          type: object
                          properties:
                            coding:
                              type: array
                              items:
                                type: object
                                properties:
                                  system:
                                    type: string
                                    example: https://fhir.nhs.uk/CodeSystem/Spine-ErrorOrWarningCode
                                  code:
                                    type: string
                                    example: VALIDATION_ERROR
                                  display:
                                    type: string
                                    example: The supplied category was not recognised by the API.
                        diagnostics:
                          type: string
                          example: 'HEALTHCHECKS is not a category that is supported by the API'
                        location:
                          type: array
                          items:
                            type: string
                            example: 'parameters/category'
        '500':
          description: Internal server error.
          content:
            application/fhir+json:
              schema:
                type: object
                properties:
                  resourceType:
                    type: string
                    example: OperationOutcome
                  id:
                    type: string
                    example: rrt-2959959087381887325-c-geu2-24001-77777777-1
                  meta:
                    type: object
                    properties:
                      lastUpdated:
                        type: string
                        example: 2025-02-10T13:40:00+00:00
                  issue:
                    type: array
                    items:
                      type: object
                      properties:
                        severity:
                          type: string
                          example: "error"
                        code:
                          type: string
                          example: processing
                        details:
                          type: object
                          properties:
                            coding:
                              type: array
                              items:
                                type: object
                                properties:
                                  system:
                                    type: string
                                    example: https://fhir.nhs.uk/CodeSystem/Spine-ErrorOrWarningCode
                                  code:
                                    type: string
                                    example: SERVICE_ERROR
                                  display:
                                    type: string
                                    example: 'An unknown error occurred processing this request. Contact us for assistance diagnosing this issue: https://digital.nhs.uk/developer/help-and-support quoting the id included in this message'
                        diagnostics:
                          type: string
                          example: 'No diagnostics available'
                        location:
                          type: array
                          items:
                            type: string
                            example: 'parameters/category'

################################################################################
#                                 Components                                  #
################################################################################
components:
    securitySchemes:
      nhs-login-p9:
        $ref: https://proxygen.prod.api.platform.nhs.uk/components/securitySchemes/nhs-login-p9
